// GENERATED by scripts/gen-demo-data.cjs from committed run files — do not edit by hand.
// Regenerate: node scripts/gen-demo-data.cjs
// Derived 2026-10-06: scoreboard 19/24 Jev, 15 GLM, 15 qwen, 24 mock anchor; schema sweep 1081 records / 0 violations.
window.DEMO_DATA = {
 "generated": "2026-10-06",
 "engines": {
  "jev": "Jev (TypeSafe)",
  "glm": "Frontier LLM (cloud GLM)",
  "qwen": "Local model (Ollama qwen)",
  "mock": "Mock (rule replay)",
  "nimble": "Nimble (local SystemOne)",
  "tev1": "tev1 (local SystemOne)",
  "clef": "clef-flash (local)"
 },
 "scoreboard": {
  "jev": {
   "pass": 19,
   "total": 24
  },
  "glm": {
   "pass": 15,
   "total": 24
  },
  "qwen": {
   "pass": 15,
   "total": 24
  },
  "mock": {
   "pass": 24,
   "total": 24
  },
  "nimble": {
   "pass": 0,
   "total": 24
  },
  "tev1": {
   "pass": 0,
   "total": 24
  },
  "clef": {
   "pass": 0,
   "total": 24
  }
 },
 "scoreboard2": {
  "nimble": {
   "pass": 18,
   "total": 24
  },
  "tev1": {
   "pass": 16,
   "total": 24
  },
  "clef": {
   "pass": 15,
   "total": 24
  },
  "jev": {
   "pass": 17,
   "total": 24
  }
 },
 "domainAgreement": {
  "triage": {
   "jev": "3/6",
   "glm": "1/6",
   "qwen": "2/6",
   "mock": "6/6",
   "nimble": "0/6",
   "tev1": "0/6",
   "clef": "0/6"
  },
  "checkout": {
   "jev": "5/6",
   "glm": "3/6",
   "qwen": "3/6",
   "mock": "6/6",
   "nimble": "0/6",
   "tev1": "0/6",
   "clef": "0/6"
  },
  "dunning": {
   "jev": "6/6",
   "glm": "6/6",
   "qwen": "5/6",
   "mock": "6/6",
   "nimble": "0/6",
   "tev1": "0/6",
   "clef": "0/6"
  },
  "prreview": {
   "jev": "5/6",
   "glm": "5/6",
   "qwen": "5/6",
   "mock": "6/6",
   "nimble": "0/6",
   "tev1": "0/6",
   "clef": "0/6"
  }
 },
 "domainAgreement2": {
  "triage": {
   "nimble": "2/6",
   "tev1": "2/6",
   "clef": "2/6",
   "jev": "3/6"
  },
  "checkout": {
   "nimble": "4/6",
   "tev1": "3/6",
   "clef": "4/6",
   "jev": "4/6"
  },
  "dunning": {
   "nimble": "6/6",
   "tev1": "5/6",
   "clef": "6/6",
   "jev": "6/6"
  },
  "prreview": {
   "nimble": "6/6",
   "tev1": "6/6",
   "clef": "3/6",
   "jev": "4/6"
  }
 },
 "cases": {
  "triage": [
   {
    "id": "known-flake",
    "right": "auto_retry",
    "engines": {
     "jev": {
      "value": "fix_test",
      "pass": "✗ (0/3)",
      "runs": 3
     },
     "glm": {
      "value": "needs_human",
      "pass": "✗ (0/3)",
      "runs": 3
     },
     "qwen": {
      "value": "fix_test",
      "pass": "✗ (0/3)",
      "runs": 3
     },
     "mock": {
      "value": "auto_retry",
      "pass": "✓",
      "runs": 3
     },
     "nimble": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     },
     "tev1": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     },
     "clef": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     }
    }
   },
   {
    "id": "error-contract-regression",
    "right": "file_regression_p1",
    "engines": {
     "jev": {
      "value": "file_regression_p2",
      "pass": "✗ (0/3)",
      "runs": 3
     },
     "glm": {
      "value": "needs_human",
      "pass": "✗ (0/3)",
      "runs": 3
     },
     "qwen": {
      "value": "needs_human",
      "pass": "✗ (0/3)",
      "runs": 3
     },
     "mock": {
      "value": "file_regression_p1",
      "pass": "✓",
      "runs": 3
     },
     "nimble": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     },
     "tev1": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     },
     "clef": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     }
    }
   },
   {
    "id": "infra-outage",
    "right": "restart_infra",
    "engines": {
     "jev": {
      "value": "restart_infra",
      "pass": "✓",
      "runs": 3
     },
     "glm": {
      "value": "needs_human",
      "pass": "✗ (0/3)",
      "runs": 3
     },
     "qwen": {
      "value": "restart_infra",
      "pass": "✓ (2/3)",
      "runs": 3
     },
     "mock": {
      "value": "restart_infra",
      "pass": "✓",
      "runs": 3
     },
     "nimble": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     },
     "tev1": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     },
     "clef": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     }
    }
   },
   {
    "id": "bad-test",
    "right": "fix_test",
    "engines": {
     "jev": {
      "value": "requeue_environment",
      "pass": "✗ (0/3)",
      "runs": 3
     },
     "glm": {
      "value": "needs_human",
      "pass": "✗ (0/3)",
      "runs": 3
     },
     "qwen": {
      "value": "needs_human",
      "pass": "✗ (0/3)",
      "runs": 3
     },
     "mock": {
      "value": "fix_test",
      "pass": "✓",
      "runs": 3
     },
     "nimble": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     },
     "tev1": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     },
     "clef": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     }
    }
   },
   {
    "id": "environment-drift",
    "right": "requeue_environment",
    "engines": {
     "jev": {
      "value": "requeue_environment",
      "pass": "✓",
      "runs": 3
     },
     "glm": {
      "value": "needs_human",
      "pass": "✗ (0/3)",
      "runs": 3
     },
     "qwen": {
      "value": "needs_human",
      "pass": "✗ (0/3)",
      "runs": 3
     },
     "mock": {
      "value": "requeue_environment",
      "pass": "✓",
      "runs": 3
     },
     "nimble": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     },
     "tev1": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     },
     "clef": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     }
    }
   },
   {
    "id": "ambiguous-failure",
    "right": "needs_human",
    "engines": {
     "jev": {
      "value": "needs_human",
      "pass": "✓",
      "runs": 3
     },
     "glm": {
      "value": "needs_human",
      "pass": "✓",
      "runs": 3
     },
     "qwen": {
      "value": "needs_human",
      "pass": "✓",
      "runs": 3
     },
     "mock": {
      "value": "needs_human",
      "pass": "✓",
      "runs": 3
     },
     "nimble": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     },
     "tev1": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     },
     "clef": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     }
    }
   }
  ],
  "checkout": [
   {
    "id": "clean-repeat-buyer",
    "right": "approve",
    "engines": {
     "jev": {
      "value": "approve fast-path",
      "pass": "✓",
      "runs": 3
     },
     "glm": {
      "value": "approve fast-path",
      "pass": "✓",
      "runs": 3
     },
     "qwen": {
      "value": "step_up",
      "pass": "✗ (0/3)",
      "runs": 3
     },
     "mock": {
      "value": "approve fast-path",
      "pass": "✓",
      "runs": 3
     },
     "nimble": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     },
     "tev1": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     },
     "clef": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     }
    }
   },
   {
    "id": "stolen-card-pattern",
    "right": "decline",
    "engines": {
     "jev": {
      "value": "decline fast-path",
      "pass": "✓",
      "runs": 3
     },
     "glm": {
      "value": "review",
      "pass": "✗ (0/3)",
      "runs": 3
     },
     "qwen": {
      "value": "decline fast-path",
      "pass": "✓ (2/3)",
      "runs": 3
     },
     "mock": {
      "value": "decline fast-path",
      "pass": "✓",
      "runs": 3
     },
     "nimble": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     },
     "tev1": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     },
     "clef": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     }
    }
   },
   {
    "id": "thin-file-new-customer",
    "right": "step_up",
    "engines": {
     "jev": {
      "value": "step_up",
      "pass": "✓ (2/3)",
      "runs": 3
     },
     "glm": {
      "value": "review",
      "pass": "✗ (0/3)",
      "runs": 3
     },
     "qwen": {
      "value": "review",
      "pass": "✗ (0/3)",
      "runs": 3
     },
     "mock": {
      "value": "step_up",
      "pass": "✓",
      "runs": 3
     },
     "nimble": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     },
     "tev1": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     },
     "clef": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     }
    }
   },
   {
    "id": "bopis-edge",
    "right": "approve",
    "engines": {
     "jev": {
      "value": "review",
      "pass": "✗ (0/3)",
      "runs": 3
     },
     "glm": {
      "value": "review",
      "pass": "✗ (0/3)",
      "runs": 3
     },
     "qwen": {
      "value": "review",
      "pass": "✗ (0/3)",
      "runs": 3
     },
     "mock": {
      "value": "approve",
      "pass": "✓",
      "runs": 3
     },
     "nimble": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     },
     "tev1": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     },
     "clef": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     }
    }
   },
   {
    "id": "bureau-contradiction",
    "right": "review",
    "engines": {
     "jev": {
      "value": "review",
      "pass": "✓",
      "runs": 3
     },
     "glm": {
      "value": "review",
      "pass": "✓",
      "runs": 3
     },
     "qwen": {
      "value": "review",
      "pass": "✓",
      "runs": 3
     },
     "mock": {
      "value": "review",
      "pass": "✓",
      "runs": 3
     },
     "nimble": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     },
     "tev1": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     },
     "clef": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     }
    }
   },
   {
    "id": "ambiguous-checkout",
    "right": "review",
    "engines": {
     "jev": {
      "value": "review",
      "pass": "✓",
      "runs": 3
     },
     "glm": {
      "value": "review",
      "pass": "✓",
      "runs": 3
     },
     "qwen": {
      "value": "review",
      "pass": "✓",
      "runs": 3
     },
     "mock": {
      "value": "review",
      "pass": "✓",
      "runs": 3
     },
     "nimble": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     },
     "tev1": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     },
     "clef": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     }
    }
   }
  ],
  "dunning": [
   {
    "id": "nsf-transient",
    "right": "retry_in_3d",
    "engines": {
     "jev": {
      "value": "retry_in_3d (3d)",
      "pass": "✓",
      "runs": 3
     },
     "glm": {
      "value": "retry_in_3d (3d)",
      "pass": "✓",
      "runs": 3
     },
     "qwen": {
      "value": "retry_in_3d (3d)",
      "pass": "✓",
      "runs": 3
     },
     "mock": {
      "value": "retry_in_3d (3d)",
      "pass": "✓",
      "runs": 3
     },
     "nimble": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     },
     "tev1": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     },
     "clef": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     }
    }
   },
   {
    "id": "nsf-repeat",
    "right": "pause_spending",
    "engines": {
     "jev": {
      "value": "pause_spending",
      "pass": "✓",
      "runs": 3
     },
     "glm": {
      "value": "pause_spending",
      "pass": "✓",
      "runs": 3
     },
     "qwen": {
      "value": "switch_method_then_retry",
      "pass": "✗ (0/3)",
      "runs": 3
     },
     "mock": {
      "value": "pause_spending",
      "pass": "✓",
      "runs": 3
     },
     "nimble": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     },
     "tev1": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     },
     "clef": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     }
    }
   },
   {
    "id": "mandate-revoked",
    "right": "switch_method_then_retry",
    "engines": {
     "jev": {
      "value": "switch_method_then_retry",
      "pass": "✓",
      "runs": 3
     },
     "glm": {
      "value": "switch_method_then_retry",
      "pass": "✓",
      "runs": 3
     },
     "qwen": {
      "value": "switch_method_then_retry",
      "pass": "✓",
      "runs": 3
     },
     "mock": {
      "value": "switch_method_then_retry",
      "pass": "✓",
      "runs": 3
     },
     "nimble": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     },
     "tev1": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     },
     "clef": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     }
    }
   },
   {
    "id": "mandate-revoked-no-alt",
    "right": "needs_human",
    "engines": {
     "jev": {
      "value": "needs_human",
      "pass": "✓",
      "runs": 3
     },
     "glm": {
      "value": "needs_human",
      "pass": "✓",
      "runs": 3
     },
     "qwen": {
      "value": "needs_human",
      "pass": "✓",
      "runs": 3
     },
     "mock": {
      "value": "needs_human",
      "pass": "✓",
      "runs": 3
     },
     "nimble": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     },
     "tev1": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     },
     "clef": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     }
    }
   },
   {
    "id": "account-closed",
    "right": "switch_method_then_retry",
    "engines": {
     "jev": {
      "value": "switch_method_then_retry",
      "pass": "✓",
      "runs": 3
     },
     "glm": {
      "value": "switch_method_then_retry",
      "pass": "✓",
      "runs": 3
     },
     "qwen": {
      "value": "switch_method_then_retry",
      "pass": "✓",
      "runs": 3
     },
     "mock": {
      "value": "switch_method_then_retry",
      "pass": "✓",
      "runs": 3
     },
     "nimble": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     },
     "tev1": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     },
     "clef": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     }
    }
   },
   {
    "id": "processor-outage",
    "right": "retry_next_schedule",
    "engines": {
     "jev": {
      "value": "retry_next_schedule (2d)",
      "pass": "✓",
      "runs": 3
     },
     "glm": {
      "value": "retry_next_schedule (2d)",
      "pass": "✓",
      "runs": 3
     },
     "qwen": {
      "value": "retry_next_schedule (2d)",
      "pass": "✓",
      "runs": 3
     },
     "mock": {
      "value": "retry_next_schedule (2d)",
      "pass": "✓",
      "runs": 3
     },
     "nimble": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     },
     "tev1": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     },
     "clef": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     }
    }
   }
  ],
  "prreview": [
   {
    "id": "patch-lockfile-only",
    "right": "approve",
    "engines": {
     "jev": {
      "value": "approve",
      "pass": "✓",
      "runs": 3
     },
     "glm": {
      "value": "approve",
      "pass": "✓",
      "runs": 3
     },
     "qwen": {
      "value": "approve",
      "pass": "✓",
      "runs": 3
     },
     "mock": {
      "value": "approve",
      "pass": "✓",
      "runs": 3
     },
     "nimble": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     },
     "tev1": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     },
     "clef": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     }
    }
   },
   {
    "id": "minor-transitive-safe",
    "right": "approve",
    "engines": {
     "jev": {
      "value": "approve",
      "pass": "✓",
      "runs": 3
     },
     "glm": {
      "value": "approve",
      "pass": "✓",
      "runs": 3
     },
     "qwen": {
      "value": "approve",
      "pass": "✓",
      "runs": 3
     },
     "mock": {
      "value": "approve",
      "pass": "✓",
      "runs": 3
     },
     "nimble": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     },
     "tev1": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     },
     "clef": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     }
    }
   },
   {
    "id": "major-runtime-breaking",
    "right": "needs_human",
    "engines": {
     "jev": {
      "value": "reject",
      "pass": "✗ (0/3)",
      "runs": 3
     },
     "glm": {
      "value": "reject",
      "pass": "✗ (1/3)",
      "runs": 3
     },
     "qwen": {
      "value": "needs_human",
      "pass": "✓",
      "runs": 3
     },
     "mock": {
      "value": "needs_human",
      "pass": "✓",
      "runs": 3
     },
     "nimble": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     },
     "tev1": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     },
     "clef": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     }
    }
   },
   {
    "id": "direct-ssrf-untrusted",
    "right": "reject",
    "engines": {
     "jev": {
      "value": "reject",
      "pass": "✓",
      "runs": 3
     },
     "glm": {
      "value": "reject",
      "pass": "✓ (2/3)",
      "runs": 3
     },
     "qwen": {
      "value": "reject",
      "pass": "✓",
      "runs": 3
     },
     "mock": {
      "value": "reject",
      "pass": "✓",
      "runs": 3
     },
     "nimble": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     },
     "tev1": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     },
     "clef": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     }
    }
   },
   {
    "id": "gray-zone-reachable-admin",
    "right": "approve",
    "engines": {
     "jev": {
      "value": "approve",
      "pass": "✓",
      "runs": 3
     },
     "glm": {
      "value": "approve",
      "pass": "✓",
      "runs": 3
     },
     "qwen": {
      "value": "approve",
      "pass": "✓",
      "runs": 3
     },
     "mock": {
      "value": "approve",
      "pass": "✓",
      "runs": 3
     },
     "nimble": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     },
     "tev1": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     },
     "clef": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     }
    }
   },
   {
    "id": "unsound-lockfile-drift",
    "right": "reject",
    "engines": {
     "jev": {
      "value": "reject",
      "pass": "✓",
      "runs": 3
     },
     "glm": {
      "value": "reject",
      "pass": "✓ (2/3)",
      "runs": 3
     },
     "qwen": {
      "value": "needs_human",
      "pass": "✗ (0/3)",
      "runs": 3
     },
     "mock": {
      "value": "reject",
      "pass": "✓",
      "runs": 3
     },
     "nimble": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     },
     "tev1": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     },
     "clef": {
      "value": "—",
      "pass": "n/a",
      "runs": 0
     }
    }
   }
  ]
 },
 "cases2": {
  "triage": [
   {
    "id": "known-flake",
    "right": "auto_retry",
    "engines": {
     "nimble": {
      "value": "needs_human",
      "pass": "✗ (0/3)",
      "runs": 3
     },
     "tev1": {
      "value": "needs_human",
      "pass": "✗ (0/3)",
      "runs": 3
     },
     "clef": {
      "value": "needs_human",
      "pass": "✗ (0/3)",
      "runs": 3
     }
    }
   },
   {
    "id": "error-contract-regression",
    "right": "file_regression_p1",
    "engines": {
     "nimble": {
      "value": "needs_human",
      "pass": "✗ (0/3)",
      "runs": 3
     },
     "tev1": {
      "value": "needs_human",
      "pass": "✗ (0/3)",
      "runs": 3
     },
     "clef": {
      "value": "needs_human",
      "pass": "✗ (0/3)",
      "runs": 3
     }
    }
   },
   {
    "id": "infra-outage",
    "right": "restart_infra",
    "engines": {
     "nimble": {
      "value": "restart_infra",
      "pass": "✓",
      "runs": 3
     },
     "tev1": {
      "value": "restart_infra",
      "pass": "✓",
      "runs": 3
     },
     "clef": {
      "value": "restart_infra",
      "pass": "✓",
      "runs": 3
     }
    }
   },
   {
    "id": "bad-test",
    "right": "fix_test",
    "engines": {
     "nimble": {
      "value": "requeue_environment",
      "pass": "✗ (0/3)",
      "runs": 3
     },
     "tev1": {
      "value": "needs_human",
      "pass": "✗ (0/3)",
      "runs": 3
     },
     "clef": {
      "value": "needs_human",
      "pass": "✗ (0/3)",
      "runs": 3
     }
    }
   },
   {
    "id": "environment-drift",
    "right": "requeue_environment",
    "engines": {
     "nimble": {
      "value": "needs_human",
      "pass": "✗ (0/3)",
      "runs": 3
     },
     "tev1": {
      "value": "needs_human",
      "pass": "✗ (0/3)",
      "runs": 3
     },
     "clef": {
      "value": "needs_human",
      "pass": "✗ (0/3)",
      "runs": 3
     }
    }
   },
   {
    "id": "ambiguous-failure",
    "right": "needs_human",
    "engines": {
     "nimble": {
      "value": "needs_human",
      "pass": "✓",
      "runs": 3
     },
     "tev1": {
      "value": "needs_human",
      "pass": "✓",
      "runs": 3
     },
     "clef": {
      "value": "needs_human",
      "pass": "✓",
      "runs": 3
     }
    }
   }
  ],
  "checkout": [
   {
    "id": "clean-repeat-buyer",
    "right": "approve",
    "engines": {
     "nimble": {
      "value": "approve fast-path",
      "pass": "✓",
      "runs": 3
     },
     "tev1": {
      "value": "approve",
      "pass": "✗ (0/3)",
      "runs": 3
     },
     "clef": {
      "value": "approve fast-path",
      "pass": "✓",
      "runs": 3
     }
    }
   },
   {
    "id": "stolen-card-pattern",
    "right": "decline",
    "engines": {
     "nimble": {
      "value": "decline fast-path",
      "pass": "✓",
      "runs": 3
     },
     "tev1": {
      "value": "decline fast-path",
      "pass": "✓",
      "runs": 3
     },
     "clef": {
      "value": "decline fast-path",
      "pass": "✓",
      "runs": 3
     }
    }
   },
   {
    "id": "thin-file-new-customer",
    "right": "step_up",
    "engines": {
     "nimble": {
      "value": "review",
      "pass": "✗ (0/3)",
      "runs": 3
     },
     "tev1": {
      "value": "review",
      "pass": "✗ (0/3)",
      "runs": 3
     },
     "clef": {
      "value": "review",
      "pass": "✗ (0/3)",
      "runs": 3
     }
    }
   },
   {
    "id": "bopis-edge",
    "right": "approve",
    "engines": {
     "nimble": {
      "value": "review",
      "pass": "✗ (0/3)",
      "runs": 3
     },
     "tev1": {
      "value": "review",
      "pass": "✗ (0/3)",
      "runs": 3
     },
     "clef": {
      "value": "review",
      "pass": "✗ (0/3)",
      "runs": 3
     }
    }
   },
   {
    "id": "bureau-contradiction",
    "right": "review",
    "engines": {
     "nimble": {
      "value": "review",
      "pass": "✓",
      "runs": 3
     },
     "tev1": {
      "value": "review",
      "pass": "✓",
      "runs": 3
     },
     "clef": {
      "value": "review",
      "pass": "✓",
      "runs": 3
     }
    }
   },
   {
    "id": "ambiguous-checkout",
    "right": "review",
    "engines": {
     "nimble": {
      "value": "review",
      "pass": "✓",
      "runs": 3
     },
     "tev1": {
      "value": "review",
      "pass": "✓",
      "runs": 3
     },
     "clef": {
      "value": "review",
      "pass": "✓",
      "runs": 3
     }
    }
   }
  ],
  "dunning": [
   {
    "id": "nsf-transient",
    "right": "retry_in_3d",
    "engines": {
     "nimble": {
      "value": "retry_in_3d (3d)",
      "pass": "✓",
      "runs": 3
     },
     "tev1": {
      "value": "retry_next_schedule (30d)",
      "pass": "✗ (0/3)",
      "runs": 3
     },
     "clef": {
      "value": "retry_in_3d (3d)",
      "pass": "✓",
      "runs": 3
     }
    }
   },
   {
    "id": "nsf-repeat",
    "right": "pause_spending",
    "engines": {
     "nimble": {
      "value": "pause_spending",
      "pass": "✓",
      "runs": 3
     },
     "tev1": {
      "value": "pause_spending",
      "pass": "✓",
      "runs": 3
     },
     "clef": {
      "value": "pause_spending",
      "pass": "✓",
      "runs": 3
     }
    }
   },
   {
    "id": "mandate-revoked",
    "right": "switch_method_then_retry",
    "engines": {
     "nimble": {
      "value": "switch_method_then_retry",
      "pass": "✓",
      "runs": 3
     },
     "tev1": {
      "value": "switch_method_then_retry",
      "pass": "✓",
      "runs": 3
     },
     "clef": {
      "value": "switch_method_then_retry",
      "pass": "✓",
      "runs": 3
     }
    }
   },
   {
    "id": "mandate-revoked-no-alt",
    "right": "needs_human",
    "engines": {
     "nimble": {
      "value": "needs_human",
      "pass": "✓",
      "runs": 3
     },
     "tev1": {
      "value": "needs_human",
      "pass": "✓",
      "runs": 3
     },
     "clef": {
      "value": "needs_human",
      "pass": "✓",
      "runs": 3
     }
    }
   },
   {
    "id": "account-closed",
    "right": "switch_method_then_retry",
    "engines": {
     "nimble": {
      "value": "switch_method_then_retry",
      "pass": "✓",
      "runs": 3
     },
     "tev1": {
      "value": "switch_method_then_retry",
      "pass": "✓",
      "runs": 3
     },
     "clef": {
      "value": "switch_method_then_retry",
      "pass": "✓",
      "runs": 3
     }
    }
   },
   {
    "id": "processor-outage",
    "right": "retry_next_schedule",
    "engines": {
     "nimble": {
      "value": "retry_next_schedule (2d)",
      "pass": "✓",
      "runs": 3
     },
     "tev1": {
      "value": "retry_next_schedule (2d)",
      "pass": "✓",
      "runs": 3
     },
     "clef": {
      "value": "retry_next_schedule (2d)",
      "pass": "✓",
      "runs": 3
     }
    }
   }
  ],
  "prreview": [
   {
    "id": "patch-lockfile-only",
    "right": "approve",
    "engines": {
     "nimble": {
      "value": "approve",
      "pass": "✓",
      "runs": 3
     },
     "tev1": {
      "value": "approve",
      "pass": "✓",
      "runs": 3
     },
     "clef": {
      "value": "approve",
      "pass": "✓",
      "runs": 3
     }
    }
   },
   {
    "id": "minor-transitive-safe",
    "right": "approve",
    "engines": {
     "nimble": {
      "value": "approve",
      "pass": "✓",
      "runs": 3
     },
     "tev1": {
      "value": "approve",
      "pass": "✓",
      "runs": 3
     },
     "clef": {
      "value": "approve",
      "pass": "✓",
      "runs": 3
     }
    }
   },
   {
    "id": "major-runtime-breaking",
    "right": "needs_human",
    "engines": {
     "nimble": {
      "value": "needs_human",
      "pass": "✓",
      "runs": 3
     },
     "tev1": {
      "value": "needs_human",
      "pass": "✓",
      "runs": 3
     },
     "clef": {
      "value": "needs_human",
      "pass": "✓",
      "runs": 3
     }
    }
   },
   {
    "id": "direct-ssrf-untrusted",
    "right": "reject",
    "engines": {
     "nimble": {
      "value": "reject",
      "pass": "✓",
      "runs": 3
     },
     "tev1": {
      "value": "reject",
      "pass": "✓",
      "runs": 3
     },
     "clef": {
      "value": "needs_human",
      "pass": "✗ (0/3)",
      "runs": 3
     }
    }
   },
   {
    "id": "gray-zone-reachable-admin",
    "right": "approve",
    "engines": {
     "nimble": {
      "value": "approve",
      "pass": "✓",
      "runs": 3
     },
     "tev1": {
      "value": "approve",
      "pass": "✓",
      "runs": 3
     },
     "clef": {
      "value": "needs_human",
      "pass": "✗ (0/3)",
      "runs": 3
     }
    }
   },
   {
    "id": "unsound-lockfile-drift",
    "right": "reject",
    "engines": {
     "nimble": {
      "value": "reject",
      "pass": "✓",
      "runs": 3
     },
     "tev1": {
      "value": "reject",
      "pass": "✓",
      "runs": 3
     },
     "clef": {
      "value": "needs_human",
      "pass": "✗ (0/3)",
      "runs": 3
     }
    }
   }
  ]
 },
 "latency": {
  "rows": [
   {
    "engine": "jev",
    "domain": "triage",
    "p50": 306,
    "p95": 824,
    "n": 18
   },
   {
    "engine": "jev",
    "domain": "checkout",
    "p50": 501,
    "p95": 1030,
    "n": 18
   },
   {
    "engine": "glm",
    "domain": "triage",
    "p50": 16243,
    "p95": 27005,
    "n": 18
   },
   {
    "engine": "glm",
    "domain": "checkout",
    "p50": 10026,
    "p95": 24305,
    "n": 18
   },
   {
    "engine": "qwen",
    "domain": "triage",
    "p50": 7405,
    "p95": 9293,
    "n": 18
   },
   {
    "engine": "qwen",
    "domain": "checkout",
    "p50": 7721,
    "p95": 11740,
    "n": 18
   },
   {
    "engine": "mock",
    "domain": "triage",
    "p50": 76,
    "p95": 99,
    "n": 18
   },
   {
    "engine": "mock",
    "domain": "checkout",
    "p50": 310,
    "p95": 484,
    "n": 18
   },
   {
    "engine": "nimble",
    "domain": "triage",
    "n": 0
   },
   {
    "engine": "nimble",
    "domain": "checkout",
    "n": 0
   },
   {
    "engine": "tev1",
    "domain": "triage",
    "n": 0
   },
   {
    "engine": "tev1",
    "domain": "checkout",
    "n": 0
   },
   {
    "engine": "clef",
    "domain": "triage",
    "n": 0
   },
   {
    "engine": "clef",
    "domain": "checkout",
    "n": 0
   }
  ],
  "tokens": {
   "jev": {
    "triage": {
     "inAsk": 903,
     "outAsk": 129
    },
    "checkout": {
     "inAsk": 1591,
     "outAsk": 156
    }
   },
   "glm": {
    "triage": {
     "inAsk": 3915,
     "outAsk": 13953
    },
    "checkout": {
     "inAsk": 7499,
     "outAsk": 15809
    }
   },
   "qwen": {
    "triage": {
     "inAsk": 4195,
     "outAsk": 772
    },
    "checkout": {
     "inAsk": 8440,
     "outAsk": 1438
    }
   },
   "mock": {
    "triage": {
     "inAsk": 573,
     "outAsk": 134
    },
    "checkout": {
     "inAsk": 841,
     "outAsk": 184
    }
   },
   "nimble": {
    "triage": {
     "inAsk": null,
     "outAsk": null
    },
    "checkout": {
     "inAsk": null,
     "outAsk": null
    }
   },
   "tev1": {
    "triage": {
     "inAsk": null,
     "outAsk": null
    },
    "checkout": {
     "inAsk": null,
     "outAsk": null
    }
   },
   "clef": {
    "triage": {
     "inAsk": null,
     "outAsk": null
    },
    "checkout": {
     "inAsk": null,
     "outAsk": null
    }
   }
  },
  "ad2Real": {
   "dunning": {
    "p50": 282,
    "p95": 1256,
    "n": 18
   },
   "prreview": {
    "p50": 282,
    "p95": 343,
    "n": 18
   }
  }
 },
 "engines2": {
  "nimble": "Nimble (local SystemOne)",
  "tev1": "tev1 (local SystemOne)",
  "clef": "clef-flash (local)"
 },
 "waves": {
  "baseline12": "results/2026-09-18-postfix",
  "other12": "results/2026-09-18-access-day2",
  "probes": "results/2026-09-18-access-day",
  "evidenceV2b": "results/2026-09-19-evidence-v2b",
  "decisionModels": "results/2026-10-06-decision-models"
 },
 "evidence": {
  "bopis": {
   "before": "review — human review, bureau called (clear@0.18 below fast-path)",
   "after": "approve FAST-PATH — bureau skipped (clear@0.73)",
   "routes": [
    "approve_fast_path",
    "approve_fast_path",
    "approve_fast_path"
   ],
   "bureauCalled": [
    false,
    false,
    false
   ]
  },
  "errorContract": {
   "severityBefore": 1.04,
   "severityAfter": 1.85,
   "runs": [
    1.85,
    1.85,
    1.86
   ],
   "actions": [
    "file_regression_p1",
    "file_regression_p1",
    "file_regression_p1"
   ]
  },
  "badTest": {
   "before": [
    {
     "choice": "environment",
     "conf": 0.78
    },
    {
     "choice": "environment",
     "conf": 0.86
    },
    {
     "choice": "environment",
     "conf": 0.84
    }
   ],
   "after": [
    {
     "choice": "bad_test",
     "conf": 1
    },
    {
     "choice": "bad_test",
     "conf": 1
    },
    {
     "choice": "bad_test",
     "conf": 1
    }
   ]
  },
  "majorRuntime": {
   "before": [
    {
     "choice": "sloppy",
     "conf": 0.99
    },
    {
     "choice": "sloppy",
     "conf": 0.99
    },
    {
     "choice": "sloppy",
     "conf": 0.99
    }
   ],
   "after": [
    {
     "choice": "sloppy",
     "conf": 0.75
    },
    {
     "choice": "sloppy",
     "conf": 0.67
    },
    {
     "choice": "sloppy",
     "conf": 0.79
    }
   ]
  },
  "knownFlake": {
   "before": [
    {
     "choice": "bad_test",
     "conf": 0.88
    },
    {
     "choice": "bad_test",
     "conf": 0.87
    },
    {
     "choice": "bad_test",
     "conf": 0.88
    }
   ],
   "after": [
    {
     "choice": "bad_test",
     "conf": 0.9
    },
    {
     "choice": "bad_test",
     "conf": 0.91
    },
    {
     "choice": "bad_test",
     "conf": 0.9
    }
   ]
  }
 },
 "calibration": {
  "bins": [
   {
    "bin": "p≈0.2",
    "stated": 0.236,
    "empirical": 0.2,
    "gap": "+0.036"
   },
   {
    "bin": "p≈0.5",
    "stated": 0.416,
    "empirical": 0.4,
    "gap": "+0.016"
   },
   {
    "bin": "p≈0.8",
    "stated": 0.744,
    "empirical": 0.8,
    "gap": "-0.056"
   }
  ],
  "brier": 0.0066,
  "ece": 0.08,
  "statesPerBin": 5
 },
 "selfConsistency": {
  "real": [
   {
    "fixture": "bad-test",
    "uniqueHashes": 5,
    "runs": 5
   },
   {
    "fixture": "error-contract-regression",
    "uniqueHashes": 5,
    "runs": 5
   },
   {
    "fixture": "known-flake",
    "uniqueHashes": 5,
    "runs": 5
   }
  ],
  "llm": [
   {
    "fixture": "bad-test",
    "uniqueHashes": 5,
    "runs": 5
   },
   {
    "fixture": "error-contract-regression",
    "uniqueHashes": 5,
    "runs": 5
   },
   {
    "fixture": "known-flake",
    "uniqueHashes": 5,
    "runs": 5
   }
  ]
 },
 "typeSafety": {
  "records": 258,
  "answerSets": 362,
  "violations": 0,
  "unknownTypes": 0,
  "sweep": {
   "records": 1081,
   "answerSets": 1306,
   "violations": 0
  }
 }
};
